services:
  drawdb-server:
    image: node:20-alpine
    container_name: drawdb-server
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"
    networks:
      - default
    env_file:
      - .env

networks:
  default:
    driver: bridge
